import type { Metadata } from "next";
import { Unbounded, Orbitron } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Providers } from "./providers";
import { BackgroundVideo } from "@/components/ui/BackgroundVideo";
import { CustomCursor } from "@/components/ui/CustomCursor";

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body
        className={`${orbitron.variable} antialiased min-h-screen bg-background text-foreground flex flex-col font-sans overflow-x-hidden scanline cursor-none`}
      >
        <Providers>
          <CustomCursor />
          <BackgroundVideo />
          <Navbar />
          <main className="flex-1 relative z-10">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
